title: Immaculate
description: >
  A beautiful, fast, AMP-compliant Jekyll theme based on Tufte CSS.
url: "https://github.com/siawyoung/immaculate"
paginate:	2 # The number of posts to show per page on your homepage
name: "Lau Siaw Young"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
